"""GitHub Pro Suite — Advanced GitHub & Repository Automation for Zenith.

Provides Pull Request creation (gh_create_pr), AI automated code review (gh_code_review),
issues/PRs listing (gh_list_issues_prs), and GitHub release publishing (gh_release_create).
Uses gh CLI or GitHub REST API.
"""
from __future__ import annotations

import asyncio
import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..core.config import settings
from .git_dev import _run_git, _get_cwd


async def gh_create_pr(
    title: str,
    body: str = "",
    head_branch: str = "",
    base_branch: str = "main",
    repo_path: str = "",
    draft: bool = False,
) -> str:
    """Create a Pull Request on GitHub for the current repository.
    Generates a body from git commits if not provided."""
    cwd = _get_cwd(repo_path)

    # Determine head branch if not provided
    if not head_branch:
        branch_res = await _run_git(["rev-parse", "--abbrev-ref", "HEAD"], cwd=cwd)
        head_branch = branch_res.strip()

    if head_branch in ("main", "master"):
        return f"[gh] Current branch is '{head_branch}'. Create or checkout a feature branch before opening a PR."

    # Auto-generate body from git log if empty
    if not body:
        log_commits = await _run_git(["log", f"origin/{base_branch}..{head_branch}", "--oneline"], cwd=cwd)
        diff_stat = await _run_git(["diff", "--stat", f"origin/{base_branch}...{head_branch}"], cwd=cwd)
        body = f"## Summary of Changes\n\n### Commits:\n```\n{log_commits[:1500]}\n```\n\n### Files Changed:\n```\n{diff_stat[:1500]}\n```\n\n_Generated by Zenith_"

    # Use gh CLI
    cmd = ["gh", "pr", "create", "--title", title, "--body", body, "--head", head_branch, "--base", base_branch]
    if draft:
        cmd.append("--draft")

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=str(cwd),
        )
        stdout, stderr = await proc.communicate()
        out = stdout.decode(errors="replace").strip()
        err = stderr.decode(errors="replace").strip()

        if proc.returncode == 0:
            return f"✅ Pull Request created:\n  {out}"

        # If gh CLI not auth'd or fails, report cleanly
        return f"[gh pr create failed]: {err or out}"
    except Exception as exc:
        return f"[gh error]: {exc}"


async def gh_code_review(base_branch: str = "main", repo_path: str = "") -> str:
    """Perform an automated code review on current uncommitted changes or branch diff against base_branch."""
    cwd = _get_cwd(repo_path)

    # Check uncommitted diff first
    diff = await _run_git(["diff"], cwd=cwd)
    diff_type = "Uncommitted Working Directory Changes"

    if not diff.strip():
        # Check branch diff against base_branch
        head_branch = (await _run_git(["rev-parse", "--abbrev-ref", "HEAD"], cwd=cwd)).strip()
        diff = await _run_git(["diff", f"{base_branch}...{head_branch}"], cwd=cwd)
        diff_type = f"Branch Diff ({head_branch} vs {base_branch})"

    if not diff.strip():
        return f"No code diff found for review ({diff_type})."

    # Truncate diff if huge
    truncated = False
    if len(diff) > 8000:
        diff = diff[:8000] + "\n... [diff truncated for review]"
        truncated = True

    # Run code review pass via AI provider
    try:
        from ..core import provider
        sys_prompt = (
            "You are a Senior Principal Software Engineer performing a rigorous code review. "
            "Analyze the provided Git diff for:\n"
            "1. 🐛 Potential bugs, race conditions, memory leaks, or null dereferences\n"
            "2. 🔒 Security vulnerabilities or unsafe inputs\n"
            "3. ⚡ Performance bottlenecks or inefficient queries/loops\n"
            "4. 🎨 Readability, architecture, and maintainability improvement\n\n"
            "Structure your review clearly with bullet points and specific code lines."
        )
        review_text = await provider.chat_once(
            "standard",
            [
                {"role": "system", "content": sys_prompt},
                {"role": "user", "content": f"Please review this diff:\n\n{diff}"}
            ],
            max_tokens=1500,
        )

        return f"### 🔍 AI Code Review ({diff_type}):\n\n{review_text}"
    except Exception as exc:
        return f"[code_review error]: {exc}"


async def gh_list_issues_prs(repo: str = "", state: str = "open") -> str:
    """List open or closed Issues and PRs for a repository or current repo using gh CLI."""
    cmd_issues = ["gh", "issue", "list", "--state", state, "--limit", "10"]
    cmd_prs = ["gh", "pr", "list", "--state", state, "--limit", "10"]

    if repo:
        cmd_issues.extend(["--repo", repo])
        cmd_prs.extend(["--repo", repo])

    cwd = settings.workspace_dir

    try:
        # Run gh issue list
        proc1 = await asyncio.create_subprocess_exec(
            *cmd_issues, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL, cwd=str(cwd)
        )
        out1, _ = await proc1.communicate()
        issues_text = out1.decode(errors="replace").strip()

        # Run gh pr list
        proc2 = await asyncio.create_subprocess_exec(
            *cmd_prs, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL, cwd=str(cwd)
        )
        out2, _ = await proc2.communicate()
        prs_text = out2.decode(errors="replace").strip()

        res = []
        if issues_text:
            res.append(f"**Issues ({state})**:\n{issues_text}")
        else:
            res.append(f"**Issues ({state})**: None")

        if prs_text:
            res.append(f"**Pull Requests ({state})**:\n{prs_text}")
        else:
            res.append(f"**Pull Requests ({state})**: None")

        return "\n\n".join(res)
    except Exception as exc:
        return f"[gh list error]: {exc}"


async def gh_release_create(
    tag: str,
    title: str = "",
    notes: str = "",
    asset_path: str = "",
    repo_path: str = "",
) -> str:
    """Create a GitHub Release with optional asset attachment."""
    cwd = _get_cwd(repo_path)
    title = title or tag

    cmd = ["gh", "release", "create", tag, "--title", title]
    if notes:
        cmd.extend(["--notes", notes])
    else:
        cmd.append("--generate-notes")

    if asset_path and Path(asset_path).exists():
        cmd.append(asset_path)

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE, cwd=str(cwd)
        )
        stdout, stderr = await proc.communicate()
        out = stdout.decode(errors="replace").strip()
        err = stderr.decode(errors="replace").strip()

        if proc.returncode == 0:
            return f"🚀 GitHub Release **{tag}** created:\n  {out}"
        return f"[gh release failed]: {err or out}"
    except Exception as exc:
        return f"[gh release error]: {exc}"
